# Generated by Django 4.0.4 on 2022-05-23 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('ID', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('GPA', models.DecimalField(decimal_places=3, max_digits=4)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField(max_length=11)),
                ('Level', models.IntegerField(max_length=1)),
                ('Date', models.DateField()),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
