# Generated by Django 4.0.4 on 2022-05-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Date',
            new_name='DateOfBirth',
        ),
        migrations.AlterField(
            model_name='student',
            name='Level',
            field=models.CharField(choices=[('First Level', 'First Level'), ('Second Level', 'Second Level'), ('Third Level', 'Third Level'), ('Fourth Level', 'Fourth Level')], max_length=12),
        ),
    ]
