# Generated by Django 4.0.4 on 2022-05-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_date_student_dateofbirth_alter_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Active',
        ),
    ]
