# Generated by Django 4.0.4 on 2022-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_gender_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=11),
        ),
    ]
