# Generated by Django 4.0.4 on 2022-05-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateOfBirth',
            field=models.CharField(max_length=30),
        ),
    ]
